stages:
    - build
    - test
    - coverage
    - packing

debian11_lua53:build:
    stage: build
    image: registry.gitlab.com/thislight/hussar:debian11_lua53_git
    script:
        - luarocks make

alpine3.12_lua54:build:
    stage: build
    image: registry.gitlab.com/thislight/hussar:alpine3d12_lua54_git
    script:
        - luarocks make

debian11_lua53:test:
    stage: test
    image: registry.gitlab.com/thislight/hussar:debian11_lua53_git
    needs: ['debian11_lua53:build']
    before_script:
        - luarocks make
    script:
        - busted

alpine3.12_lua54:test:
    stage: test
    image: registry.gitlab.com/thislight/hussar:alpine3d12_lua54_git
    needs: ['alpine3.12_lua54:build']
    before_script:
        - luarocks make
    script:
        - busted

alpine3.12_lua54:coverage:
    stage: coverage
    image: registry.gitlab.com/thislight/hussar:alpine3d12_lua54_git
    needs: ['alpine3.12_lua54:build']
    before_script:
        - luarocks make
    script:
        - busted -c
        - luacov away
        - cat luacov.report.out
    coverage: '/^Total\s+\d+\s+\d+\s+(\d+\.?\d*\%)/'
    artifacts:
        paths:
            - luacov.report.out
            - luacov.stats.out

packing_git_src_rock:
    stage: packing
    image: registry.gitlab.com/thislight/hussar:alpine3d12_lua54_git
    needs: ['alpine3.12_lua54:build']
    script:
        - luarocks pack away-git-0.rockspec
    artifacts:
        paths:
            - away-git-0.src.rock